version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/mysql:8.0.4
        command:
          [
            "mysqld",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_bin",
          ]
        environment:
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_USER: root
          - MYSQL_PASSWORD: test
    steps:
      - checkout
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt update
            sudo apt-get install default-mysql-client
      - run:
          name: Wait for db
          command: python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000
      - run:
          name: build
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: test
          command: |
            . venv/bin/activate
            python3 manage.py test && flake8
workflows:
  version: 2
  test:
    jobs:
      - build
